import { Contract } from '@/lib/types';

export const CONTRACTS: Contract[] = [
  {
    id: 'cnt-1',
    employeeId: 'emp-1',
    employeeName: 'Rohan Sharma',
    contractReference: 'CNT-2024-ENG-042',
    wage: 43500,
    startDate: '2024-04-01',
    endDate: '2027-03-31',
    department: 'Engineering',
    jobPosition: 'Senior Software Engineer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-2',
    employeeId: 'emp-2',
    employeeName: 'Priya Sundaram',
    contractReference: 'CNT-2023-HR-008',
    wage: 75000,
    startDate: '2023-08-01',
    endDate: '2026-07-31',
    department: 'Human Resources',
    jobPosition: 'People Operations Manager',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-3',
    employeeId: 'emp-3',
    employeeName: 'Vikram Malhotra',
    contractReference: 'CNT-2023-FIN-015',
    wage: 58000,
    startDate: '2023-02-10',
    endDate: '2026-02-09',
    department: 'Finance & Payroll',
    jobPosition: 'Senior Payroll Specialist',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-4',
    employeeId: 'emp-4',
    employeeName: 'Ananya Deshmukh',
    contractReference: 'CNT-2022-FIN-001',
    wage: 115000,
    startDate: '2022-01-15',
    endDate: '2027-01-14',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Operations Director',
    salaryStructureId: 'str-3',
    salaryStructureName: 'Executive Leadership Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-5',
    employeeId: 'emp-5',
    employeeName: 'Rajesh Patel',
    contractReference: 'CNT-2021-ADM-001',
    wage: 145000,
    startDate: '2021-03-01',
    endDate: '2028-02-29',
    department: 'Operations',
    jobPosition: 'Global HR Operations Administrator',
    salaryStructureId: 'str-3',
    salaryStructureName: 'Executive Leadership Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-6',
    employeeId: 'emp-6',
    employeeName: 'Kavita Menon',
    contractReference: 'CNT-2023-PRD-020',
    wage: 64000,
    startDate: '2023-06-20',
    endDate: '2026-06-19',
    department: 'Product & Design',
    jobPosition: 'Lead Product Designer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-7',
    employeeId: 'emp-7',
    employeeName: 'Aarav Mukherjee',
    contractReference: 'CNT-2024-ENG-088',
    wage: 47000,
    startDate: '2024-01-10',
    endDate: '2027-01-09',
    department: 'Engineering',
    jobPosition: 'Full Stack Engineer',
    salaryStructureId: 'str-2',
    salaryStructureName: 'Tech Engineering Salary Structure',
    status: 'active',
    isActive: true,
  },
  {
    id: 'cnt-11',
    employeeId: 'emp-11',
    employeeName: 'Meera Nambiar',
    contractReference: 'CNT-2024-HR-044',
    wage: 37000,
    startDate: '2024-08-10',
    endDate: '2025-08-09',
    department: 'Human Resources',
    jobPosition: 'Talent Acquisition Partner',
    salaryStructureId: 'str-1',
    salaryStructureName: 'Standard Corporate Salary Structure',
    status: 'active',
    isActive: true,
    warnings: ['Missing bank details for electronic NEFT transfer'],
  },
];
