import { User } from '@/lib/types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Aravind Krishnan',
    email: 'employee.aravind@peoplepay360.demo',
    role: 'employee',
    roleTitle: 'Employee',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    employeeId: 'EMP-001',
    department: 'Engineering',
    jobPosition: 'Senior Software Engineer',
  },
  {
    id: 'usr-2',
    name: 'Priya Sundaram',
    email: 'sri7685234360.demo',
    role: 'hr_manager',
    roleTitle: 'HR Manager',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    employeeId: 'EMP-002',
    department: 'Human Resources',
    jobPosition: 'People Operations Manager',
  },
  {
    id: 'usr-3',
    name: 'Neha Gupta',
    email: 'payroll.user@peoplepay360.demo',
    role: 'payroll_user',
    roleTitle: 'HR Payroll User',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    employeeId: 'EMP-004',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Specialist',
  },
  {
    id: 'usr-4',
    name: 'Rajesh Kulkarni',
    email: 'payroll.mgr@peoplepay360.demo',
    role: 'payroll_manager',
    roleTitle: 'HR Payroll Manager',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    employeeId: 'EMP-003',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Operations Director',
  },
  {
    id: 'usr-5',
    name: 'Vikramaditya Sharma',
    email: 'admin@peoplepay360.demo',
    role: 'admin',
    roleTitle: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    employeeId: 'ADM-001',
    department: 'Executive Administration',
    jobPosition: 'Global HR Operations Administrator',
  },
];
